##Experiment 2a

```{r echo = FALSE}
#Creating a table for the comparisons
contrastsSEL <- as.data.frame(table_glht(model_SEL_mcp))
contrastsSEL <- cbind(rownames(contrastsSEL), data.frame(contrastsSEL, row.names=NULL))
contrastsSEL <- contrastsSEL %>% 
  separate("rownames(contrastsSEL)", c("`Contrast trial type`", "`Trial type`"), sep = " - ") %>%
  dplyr::select(c("`Trial type`", "`Contrast trial type`":"Pr...z.."), 
                `Mean difference` = Estimate,
                `Std. error` = Std..Error,
                `p value` = Pr...z..)
contrastsSEL <- contrastsSEL[c(1:3, 7:8, 12, 19:21),]
`Trial type` <- c("Word vs PW",
                  "~",
                  "~",
                  "Word vs In FW",
                  "~",
                  "Word vs Med FW",
                  "PW vs In FW",
                  "~",
                  "PW vs Med FW")

contrastsSEL <- dplyr::select(contrastsSEL, c("`Contrast trial type`":"p value"))
contrastsSEL <- cbind(`Trial type`, contrastsSEL)
round(contrastsSEL$`p value`, digits = 3) -> contrastsSEL$`p value`
contrastsSEL$`p value` <- format.pval(contrastsSEL$`p value`, eps = .001)
```




```{r results="asis", echo = FALSE, include = TRUE, out.width = "\\textwidth"}
apa_table(contrastsSEL,
          caption = "Multiple comparisons of mixed effects model results, Experiment 2a",
          row.names = FALSE)
```



```{r echo = FALSE}
sel_rt_means <- sel_RT %>% group_by(SubjectID, PairCode) %>% summarise(RT = mean(RT)) %>% group_by(PairCode) %>% summarise(Mean = mean(RT), SD = sd(RT)) %>% mutate(PairCode = factor(PairCode, labels = c("Word vs PW","Word vs Initial FW","Word vs Medial FW", "Word vs Final FW", "PW vs Initial FW", "PW vs Medial FW", "PW vs Final FW")))
```


```{r results = "asis", echo = FALSE, include = TRUE, out.width = "\\textwidth"}
apa_table(sel_rt_means,
          caption = "Means and standard deviations for RT, Experiment 2a")
```


```{r echo = FALSE}
x <- coef(summary(model_SEL_RT))
`Fixed Effect` <- c("Intercept",
                    "Word vs Initial FW",
                    "Word vs Medial FW",
                    "Word vs Final FW",
                    "PW vs Initial FW",
                    "PW vs Medial FW",
                    "PW vs Final FW",
                    "Trial",
                    "Target Location [2]",
                    "Trial x Word vs Initial FW",
                    "Trial x Word vs Medial FW",
                    "Trial x Word vs Final FW",
                    "Trial x PW vs Initial FW",
                    "Trial x PW vs Medial FW",
                    "Trial x PW vs Final FW")
x <- cbind(x, `Fixed Effect`)
rownames(x) <- NULL
x <- x[,c(6,1:5)]
x <- as.data.frame(x)
x <- 
  x %>% 
  mutate(`Pr(>|t|)` = format.pval(round(as.numeric(as.character(`Pr(>|t|)`)), digits = 2), eps = .001),
         Estimate = round(as.numeric(as.character(Estimate)),digits = 2),
         `t value` = round(as.numeric(as.character(`t value`)),digits = 2),
         `Std. Error` = round(as.numeric(as.character(`Std. Error`)),digits = 2),
         df = round(as.numeric(as.character(df)),digits = 2)) %>% 
  rename(`p value` = `Pr(>|t|)`) 
```



```{r results="asis", echo = FALSE, include = TRUE, out.width = "\\textwidth"}
apa_table(x,
          caption = "Mixed effects model results predicting RT, Experiment 2a")
```


```{r echo = FALSE}
contrastsSEL_RT <- as.data.frame(table_glht(model_SEL_RT_mcp))
contrastsSEL_RT <- cbind(rownames(contrastsSEL_RT), data.frame(contrastsSEL_RT, row.names=NULL))
contrastsSEL_RT <- contrastsSEL_RT %>% 
  separate("rownames(contrastsSEL_RT)", c("`Contrast trial type`", "`Trial type`"), sep = " - ") %>%
  dplyr::select(c("`Trial type`", "`Contrast trial type`":"Pr...z.."), 
                `Mean difference` = Estimate,
                `Std. error` = Std..Error,
                `p value` = Pr...z..)
`Trial type` <- c("Word vs PW",
                  "~",
                  "~",
                  "~",
                  "~",
                  "~",
                  "Word vs In FW",
                  "~",
                  "~",
                  "~",
                  "~",
                  "Word vs Med FW",
                  "~",
                  "~",
                  "~",
                  "Word vs Fin FW",
                  "~",
                  "~",
                  "PW vs In FW",
                  "~",
                  "PW vs Med FW")

contrastsSEL_RT <- dplyr::select(contrastsSEL_RT, c("`Contrast trial type`":"p value"))
contrastsSEL_RT <- cbind(`Trial type`, contrastsSEL_RT)
round(contrastsSEL_RT$`p value`, digits = 3) -> contrastsSEL_RT$`p value`
contrastsSEL_RT$`p value` <- format.pval(contrastsSEL_RT$`p value`, eps = .001)
```


```{r results="asis", echo = FALSE, include = TRUE, out.width = "\\textwidth"}
apa_table(contrastsSEL_RT,
          caption = "Multiple comparisons of mixed effects model results for RT, Experiment 2a",
          row.names = FALSE)
```
